
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.4'
version_full = '34dcb3378c444f7ef195aa8073f01710fd4b7e2b'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
