
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.8'
version_full = '0a87e2bd3c79409ef6b30cef085d90a8ca4f9441'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
