# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification.proto',
  package='leap.common',
  serialized_pb='\n\x12notification.proto\x12\x0bleap.common\"\xf7\x01\n\x0cNotification\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x36\n\tcomponent\x18\x02 \x02(\x0e\x32#.leap.common.Notification.Component\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\t\x12\x12\n\nmac_method\x18\x04 \x02(\t\x12\x0b\n\x03mac\x18\x05 \x02(\x0c\x12\x12\n\nenc_method\x18\x06 \x01(\t\x12\x16\n\x0e\x65rror_occurred\x18\x07 \x01(\x08\"E\n\tComponent\x12\n\n\x06\x63lient\x10\x00\x12\x0b\n\x07soledad\x10\x01\x12\x07\n\x03\x65ip\x10\x02\x12\x0e\n\nsmtp_relay\x10\x03\x12\x06\n\x02mx\x10\x04')



_NOTIFICATION_COMPONENT = _descriptor.EnumDescriptor(
  name='Component',
  full_name='leap.common.Notification.Component',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='client', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='soledad', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='eip', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='smtp_relay', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='mx', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=214,
  serialized_end=283,
)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='leap.common.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='leap.common.Notification.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='component', full_name='leap.common.Notification.component', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='leap.common.Notification.content', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac_method', full_name='leap.common.Notification.mac_method', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac', full_name='leap.common.Notification.mac', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enc_method', full_name='leap.common.Notification.enc_method', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_occurred', full_name='leap.common.Notification.error_occurred', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NOTIFICATION_COMPONENT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=283,
)

_NOTIFICATION.fields_by_name['component'].enum_type = _NOTIFICATION_COMPONENT
_NOTIFICATION_COMPONENT.containing_type = _NOTIFICATION;
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION

class Notification(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTIFICATION

  # @@protoc_insertion_point(class_scope:leap.common.Notification)


# @@protoc_insertion_point(module_scope)
