#!/usr/bin/env python
import sys
from twisted.internet import task
from leap.common.http import HTTPClient


def main(reactor, host):
    def cb(_):
        print "OK"
    client = HTTPClient()
    return client.request(host).addCallback(cb)


task.react(main, sys.argv[1:])
